name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure and make
        run: |
          ./configure
          make

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv src/libck.a ./libck-macos12.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos12
          path: |
            include.zip
            libck-macos12.a
            LICENSE

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure and make
        run: |
          ./configure
          make

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv src/libck.a ./libck-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: libck-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.1.8/aarch64-rpi4-linux-gnu.tar.xz
          tar xf aarch64-rpi4-linux-gnu.tar.xz -C ~

      - name: Configure and make RPi
        run: |
          ./configure --profile="rpi-aarch64"
          make
          mv src/libck.a ./libck-rpi-arm64.a
        env:
          CC: ${{ env.HOME }}/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-gcc

      - name: Configure and make linux-x64
        run: |
          make clean
          ./configure --profile="x86_64"
          make
          mv src/libck.a ./libck-linux-x64.a
        env:
          CC: gcc

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libck-rpi-arm64.a
            libck-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-linux, build-macos-arm64]
    steps:
      - name: Get build output macos12
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos12

      - name: Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libck-macos12.a
            libck-rpi-arm64.a
            libck-macos-arm64.a
            libck-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
